### ISSUE TITLE
User story #10 - Edit user profile 

### ISSUE THREAD

**Issue by idamariasofie** [idamariasofie/lively#10]
As a user, I can edit my user profile to update my personal details.

Acceptance Criteria

- Edit button brings user to profile edit modal.
- User receives visual feedback that the form field areas are ready to be edited.
- Form fields prepopulated with users previously saved data.
- Database must update with user's new details.

Tasks

- [x] Create 'edit' button path
- [x] Create edit profile modal with editable form fields
- [x] Create 'Edit' button connections to push new data to database
